<form action="/auth/login" method="post">
    <table>
        <tr><td>Login: </td><td><input name="login" type="text"></td></tr>
        <tr><td>Password: </td><td><input name="password" type="password"></td></tr>
        <?php if (isset($data['message'])): ?>
            <tr><td colspan="2" style="color: red"><?=$data['message']?></td></tr>
        <?php endif; ?>
    </table>
    <input type="submit" value="Login">
</form>
