<html>
    <head>
        <meta charset="utf-8">
        <title>Todo List</title>
        <style>
            li {
                list-style-type: none;
                display: inline-block;
                background: yellow;
                margin-right: 5px;
            }

            li.active {
                background: red;
            }
        </style>
    </head>
    <body>
        <div id="header" style="height: 100px; border: black solid 1px">
            <?php if (!$_SESSION['login']): ?>
                <a href='/auth/index'>Login as admin</a>
            <?php else: ?>
                <a href='/auth/logout'>Logout</a>
            <?php endif; ?>
        </div>
        <div id="message" style="font-size: 30px; color: blueviolet">
            <?php
                if (isset($_GET['save'])) {
                    if ($_GET['save'] == 'success') {
                        echo 'Saving was successful';
                    } elseif ($_GET['save'] == 'fail') {
                        echo 'Something went wrong';
                    }
                }
            ?>
        </div>
        <div style="width: 1000px; height: 1000px; margin: auto;" id="content">
            <?php include PATH.'/app/View/' . $view . '.phtml'; ?>
        </div>
        <div id="footer"></div>
    </body>
</html>